# Generated by Django 5.2.7 on 2025-10-11 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_room_capacity_room_kitchen'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
